# Generated by Django 4.1.2 on 2022-10-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("date_of_creation", models.DateField(auto_now_add=True)),
                ("date_of_change", models.DateField(auto_now=True)),
            ],
        ),
    ]
