# Generated by Django 4.1.2 on 2022-10-25 17:58

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_group_contact_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                max_length=10, validators=[contacts.models.validate_phone]
            ),
        ),
    ]
