# Generated by Django 4.1.3 on 2022-11-18 13:11

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=contacts.models.get_icon_path
            ),
        ),
    ]
